
# ***if Condition***









<div dir="rtl">
زوج یا فرد بودن a را بررسی کرده و پیغام مناسب چاپ کنید.
</div>

In [1]:
a = 21
if a%2==0:
  print('a is even.')
else:
  print('a is odd.')

a is odd


<div dir="rtl">
آیا a عددی دو رقمی است؟</div>

In [2]:
a = 12
if (a>9) & (a<100):
  print('a has two digits.')
else:
  print("a hasn't two digits.")

a has two digits


<div dir="rtl">
آیا نامی که در متغیر name ذخیره شده با Ali شروع شده است؟</div>

In [3]:
name = 'AliReza'
if name.startswith('Ali'):
  print('Yes!')
else:
  print('No!')

Yes!


<div dir="rtl">
آیا کاراکتر x در متغیر رشته ای s وجود دارد یا خیر؟</div>

In [4]:
s = 'xavi'
if 'x' in s:
  print('s has character x.')
else:
  print("s hasn't character x.")

s has character x.


<div dir="rtl">
با داشتن شماره روز هفته نام روز را چاپ کنید.
</div>

In [5]:
weekday = 3
if weekday == 1 :
    print("Monday");
elif weekday == 2 :
    print("Tuesday")
elif(weekday == 3) :
    print("Wednesday")
elif(weekday == 4) :
    print("Thursday")
elif(weekday == 5) :
    print("Friday")
elif(weekday == 6) :
    print("Saturday")
elif (weekday == 7) :
    print("Sunday")
else :
    print("weekday is wrong!")

Wednesday


<div dir="rtl">
منفی، مثبت یا صفر بودن a را به کمک ifهای تودرتو تشخیص دهید.</div>

In [6]:
a = -2
if a>0:
  print('a is positive.')
else:
  if a == 0:
    print('a is zero.')
  else:
    print('a is negative.')

a is negative.


# ***for Condition***

<div dir="rtl">
تمام میوه های لیست fruits را چاپ کنید.</div>

In [7]:
fruits = ["apple", "banana", "cherry", "mongo"]
for f in fruits:
  print(f)

apple
banana
cherry
mongo


<div dir="rtl">
نام میوه های لیست که 5 کاراکتری هستند را چاپ نمایید.</div>

In [8]:
fruits = ["apple", "banana", "cherry", "mongo"]
for f in fruits:
  if len(f)==5:
    print(f)

apple
mongo


<div dir="rtl">
اول بودن یا نبودن عدد a را بررسی کنید.</div>

In [12]:
a = 47
prime = True
for i in range(2,int(a**0.5)+1):
  if a%i==0:
    prime = False
    break
    
if prime:    
  print(a, "is prime")
else:    
  print(a, "is not prime")

47 is prime


<div dir="rtl">
اعداد زوج دو رقمی را چاپ کنید.</div>

In [13]:
for i in range(10,100,2):
  print(i)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


<div dir="rtl">
اعداد فرد در لیست q که در موقعیت زوج هستند را چاپ نمایید. </div>

In [15]:
q = [22,32,12,55,33,13,46,8,10,2,65,31,34,101,111]
for i,j in enumerate(q):
  if (i%2==0) & (j%2==1):
    print(j)

33
65
111


<div dir="rtl">
تابعی بنویسید که طول و عرض یک مستطیل را از ورودی دریافت کند و محیط و مساحت آن را برگرداند.
</div>

In [16]:
def rectangle(x,y):
  a = x*y
  b = (x+y)*2
  return a,b

area, perimeter = rectangle(4,5)
print(area, perimeter)

20 18


<div dir="rtl">
تابعی بنویسید که یک عدد دریافت کند و اول بودن یا نبودن آن را به صورت boolean برگرداند.
</div>

In [17]:
def isprime(x):
  for i in range(2,int(x**0.5)+1):
    if x%i==0:
      return False
  
  return True


if isprime(9):
  print('prime')
else:
  print('not prime')

not prime


<div dir="rtl">
تابعی بنویسید که یک رشته دریافت کند و حضور یا عدم حضور کاراکتر x در آن را به صورت boolean برگرداند.
</div>

In [18]:
def match(s):
  for ch in s:
    if ch=='x':
      return True
  
  return False

if match('thanx python  xxxxx'):
  print('There is x in this string!!!')
else:
  print('No x here!!!')

There is x in this string!!!


#numpy

In [20]:
import numpy as np

<div dir="rtl">
دو آرایه numpy را در راستای افقی به هم بچسبانید.
</div>

In [21]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
np.hstack([a,b])

array([1, 2, 3, 5, 6, 7])

<div dir="rtl">
دو آرایه numpy را در راستای عمودی به هم بچسبانید.
</div>

In [22]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])
c = np.vstack([a,b])
c

array([[1, 2, 3],
       [5, 6, 7]])

<div dir="rtl">
عناصر دو ماتریس a و b را از هم کم کنید.
</div>

In [23]:
a = np.array ( [ [1,2] , [3,4] ] )
b = np.array ( [ [2,0] , [-5,6] ] )
np.subtract(a,b)

array([[-1,  2],
       [ 8, -2]])

<div dir="rtl">
تمام عناصر یک آرایه numpy را بر عدد 3 تقسیم کنید.
</div>

In [32]:
a = np.array( [5,6,7])
np.divide( a , 3)
# np.floor_divide( a , 3) # تقسیم صحیح

array([1.66666667, 2.        , 2.33333333])

<div dir="rtl">
تولید اعداد یک محدوده در قالب آرایه numpy
</div>

In [29]:
# np.arange(1, 13)  # بدون در نظر گرفتن گام حرکت
np.arange(1, 13, 2) # پارامتر سوم گام حرکت است

array([ 1,  3,  5,  7,  9, 11])

<div dir="rtl">
اضافه کردن یک عدد در انتهای یک آرایه numpy</div>

In [31]:
r = np.random.normal(50,5,10) # تولید 10 عدد تصادفی با میانگین 50 و انحراف معیار 5
R = np.append(r,23) # اضافه کردن عدد 23 در انتهای آرایه
R

array([48.2114126 , 35.726778  , 52.95664132, 55.87934112, 53.1013192 ,
       52.63111934, 52.74040967, 61.51553016, 51.80128259, 51.91969736,
       23.        ])